apiVersion: platform.ripple.com/v1alpha1
kind: DynamoIRSA
metadata:
  name: dynamo-irsa-test
spec:
  writeConnectionSecretToRef:
    name: dynamo-irsa-test
  resourceConfig:
    region: us-west-2
    tags:
      namespace: crossplane-system
      cluster: crossplane
  dynamoConfig:
    billingMode: PAY_PER_REQUEST
    attribute:
      - name: ID
        type: S
    hashKey: ID
